### PR TITLE
User story/#3: Create an Account with a Username, Name and Password

### PR DESCRIPTION
**Pull request by MRaeesD**
This pull request addresses User Story #3 , which focuses on allowing the user to create an account. The account is stored in a Firebase database. Firebase handles user authentication and hashing of passwords.

### CODE REVIEW

**Comment by MRaeesD** [comment]
Tests fail as the API key cold not be found. The API key will be added as a secret environment variable in GitHub, and in the workflow.

**Comment by meneerfrikkie** [comment]
After many attempts, there seems to be an issue in utilizing secrets within GitHub Workflow. My suggestion is that we remove the tests requiring access to the Firebase database, and create an issue with a "bug" label to tackle  in one of the later sprints. What does the team think?

**Comment by Irfaan-Mia** [comment]
I agree with you @meneerfrikkie lets label it as a "bug" and we will address it in the third sprint.

**Comment by MRaeesD** [comment]
> After many attempts, there seems to be an issue in utilizing secrets within GitHub Workflow. My suggestion is that we remove the tests requiring access to the Firebase database, and create an issue with a "bug" label to tackle in one of the later sprints. What does the team think?

I agree @meneerfrikkie. Also, testing functionality is difficult in the case of signup as we cannot create an account with a username that already exists. We will have to reconsider the testing methods for this section and correct it in a future sprint.

**Comment by TaahirKolia** [comment]
The database works well as accounts can be successfully created and stored in it. After creating an account the page successfully redirects to the lobby creation screen where a game can be successfully created. Tests that are in place work and code adheres to guidelines.

Future adjustments: Integrate Firebase Testing and Secrets.

**Pull request merged**
