### PR TITLE
User Story #8: See who is in the Lobby.

### PR DESCRIPTION
**Pull request by meneerfrikkie**
This pull request addresses User Story #8 (Part of Epic #15), which focuses on displaying players usernames when joining a lobby session. User Interface (UI) adjustments were made along with this Pull Request to visually enhance the displaying of usernames. I've also addressed a suggestion mentioned in Pull Request #27 where I've greyed the 'Start Game' button colour until at least 3 members have joined the lobby for which the Button colour then changes.

With regards to testing, the Playwright tests commented out initially ran and passed on my local laptop. However seem to fail when GitHub Actions attempts to run them. This will be resolved in a later sprint.

Note:
Please review the changes and provide any feedback or suggestions for improvement.

### CODE REVIEW

**Comment by MRaeesD** [comment]
When a player logs in, their username shows up in the lobby screen. 
The "Start Game" button is greyed out initially, and cannot be clicked when greyed out - as expected. 
Once at least three people join, the button turns blue and any of the people in the lobby can start the game for the entire lobby - as expected. 
If a players leaves the lobby before the game has started, and there are now fewer than three people in the lobby, the "Start Button" goes grey again, and cannot be clicked, as expected.
If multiple lobbies have been made, each one operates independently, showing only the users that have joined that specific lobby. The lobbies also work independently, so if one is affected, others are not. 

Problem Observed: If a player joins a lobby after the game has started, the lobby menu appears at the top of the screen of all players in the lobby, except the person that just joined. If this occurs, and a player presses the "Start Game" button again, the game will start for the newest joiner, but will break for everyone else that is already in the game.

**Comment by MRaeesD** [comment]
When a player logs in, their username shows up in the lobby screen.
The "Start Game" button is greyed out initially, and cannot be clicked when greyed out, as expected.
Once at least three people join, the button turns blue and any of the people in the lobby can start the game for the entire lobby, as expected.
If a players leaves the lobby before the game has started, and there are now fewer than three people in the lobby, the "Start Button" goes grey again, and cannot be clicked, as expected.
If multiple lobbies have been made, each one operates independently, showing only the users that have joined that specific lobby. The lobbies also work independently, so if one is affected, others are not.

**Comment by Irfaan-Mia** [comment]
Everything looks good. The functionality meets the requirements of the user story. The tests that were commented out need to be addressed as to why they are failing on GitHub workflow but not when you locally run the tests. The controlling of the states of which screens the users are on needs to be improved but that is scheduled for a future update.

**Review by TaahirKolia — APPROVED** [review]
The lobby list works sufficiently. When logging into an account, the username associated with the account is displayed on the lobby list once a lobby is created. When another logged in user joins the lobby, the list updates. As mentioned by Irfaan, the tests need to be addressed and further improvement needs to be made on the controlling of game states.

**Pull request merged**
